global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'smart-ecommerce-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'smart-ecommerce-backend' # <-- THIS IS THE SLEDGEHAMMER