# Server Configuration
server.port=8080

# Give the application a name
spring.application.name=smart-ecommerce-backend

# Tell Micrometer to attach this name tag to EVERY metric it sends to Prometheus
management.metrics.tags.application=${spring.application.name}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson Configuration
spring.jackson.serialization.indent-output=true

# Redis Cache
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Reveal Cache Hits and Misses
logging.level.org.springframework.cache=TRACE

# Security
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# --- Apache Kafka Configuration (Local Docker) ---
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
# Force Kafka to send messages immediately
spring.kafka.producer.properties.linger.ms=0

# --- Real SMTP Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Payment Gateways ---
stripe.api.key=${STRIPE_API_KEY}

# Expose the Prometheus endpoint
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true